# Production values for webrtc-client-sdk
# This is a YAML-formatted file for production deployments.

replicaCount: 3

image:
  repository: ghcr.io/fanoo2/webrtc-client
  pullPolicy: IfNotPresent
  tag: "1.0.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: webrtc-sdk.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: webrtc-sdk-tls
      hosts:
        - webrtc-sdk.yourdomain.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

# Node selector for production workloads
nodeSelector:
  kubernetes.io/os: linux
  node-type: production

# Tolerations for dedicated nodes
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "webrtc"
    effect: "NoSchedule"

# Pod anti-affinity for high availability
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - webrtc-client-sdk
        topologyKey: kubernetes.io/hostname

env:
  - name: NODE_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "info"

# LiveKit configuration (credentials from secrets)
livekit:
  url: "wss://your-livekit-server.com"
  apiKey: ""     # leave blank → will use webrtc-livekit-config/apiKey
  apiSecret: ""  # leave blank → will use webrtc-livekit-config/apiSecret