apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webrtc-client-sdk.fullname" . }}
  labels:
    {{- include "webrtc-client-sdk.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webrtc-client-sdk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webrtc-client-sdk.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webrtc-client-sdk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
            {{- if .Values.livekit.url }}
            - name: LIVEKIT_URL
              value: {{ .Values.livekit.url }}
            {{- end }}
            {{- if and .Values.livekit.apiKey (ne .Values.livekit.apiKey "") }}
            - name: LIVEKIT_API_KEY
              value: {{ .Values.livekit.apiKey }}
            {{- else }}
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: webrtc-livekit-config
                  key: apiKey
            {{- end }}
            {{- if and .Values.livekit.apiSecret (ne .Values.livekit.apiSecret "") }}
            - name: LIVEKIT_API_SECRET
              value: {{ .Values.livekit.apiSecret }}
            {{- else }}
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: webrtc-livekit-config
                  key: apiSecret
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}