# Default values for webrtc-client-sdk.
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: ghcr.io/fanoo2/webrtc-client
  pullPolicy: IfNotPresent
  tag: "1.0.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: webrtc-sdk.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: NODE_ENV
    value: "production"

# LiveKit configuration (should be provided via secrets)
livekit:
  url: "wss://fanno-1s7jndnl.livekit.cloud"
  apiKey: ""     # leave blank → will use webrtc-livekit-config/apiKey
  apiSecret: ""  # leave blank → will use webrtc-livekit-config/apiSecret